### ISSUE TITLE
Problem with sessionStorage in Safari

### ISSUE THREAD

**Issue by kononovspb** [robinvdvleuten/vuex-persistedstate#126]
Hello!
I found bug in Safari browser.
Max value length is 200 symbols.
If you have > 200 symbols in value, Safari trim it ...
In chrome all is ok

**Comment by robinvdvleuten** [comment]
Thanks for reporting but it's not an issue with this plugin, it's an issue with your own state handling then.

**Comment by gusjohnson** [comment]
I think I may be having the same problem, but not due to the 200 symbols problem mentioned above. It looks like Safari cuts off at 200 symbols when viewing through their dev-tools UI view, but if I run a `sessionStorage.getItem('vuex')` in the dev-tools command line I'm seeing the full value, so I don't think that's the issue.

My problem is that the state is not retained in Safari unless the developer tools are open. I've tried in a few different Vue apps and it seems consistent. This is all I'm doing to implement:

```
export default new Vuex.Store({
  state,
  modules,
  strict: wwtEnv.getEnv() !== 'prod',
  mutations,
  actions,
  plugins: [createPersistedState({ storage: window.sessionStorage })]
})
```

Seems to work just fine in Chrome/Firefox.
