### ISSUE TITLE
arrayMerger returns the same data no matter what parameter I return

### ISSUE THREAD

**Issue by Suruat** [robinvdvleuten/vuex-persistedstate#164]
**Do you want to request a *feature* or report a *bug*?**
Bug... probably)
**What is the current behavior?**
Short version: When I using `arrayMerger` option, I ended up with a state from LocalStorage, no matter what parameter I return.

Long version: My general problem I' been trying to fix is updating codebase. After update changes are not applied, until user drops data in Local Storage. So I try to use versioning to know is there a need to update local storage with the new data or not. But no matter what I returning in `arrayMerger` function, `merge` of deepmerge plugin return old data.

I'm not sure either it is a bug or I am missing something. When I edit vuex-persistedstate code in a way that `replaceState()` method directly received a result of `arrayMerger` function, it works as I expected.

**What is the expected behavior?**
Change data on Local Storage depend on what parameter of `arrayMerger` function is returned (new data: vuex state, or old one: excisted state in local storage)

**Comment by doubouil** [comment]
Can confirm this behavior, when I look to the [Options interface in index.d.ts](https://github.com/robinvdvleuten/vuex-persistedstate/blob/master/index.d.ts#L9) it seems the arrayMerger is not defined, maybe it missing somewhere else ?
Also the [default merge function parameters use clone : false](https://github.com/robinvdvleuten/vuex-persistedstate/blob/master/index.js#L61) which is flagged as [deprecated on deepmerge](https://www.npmjs.com/package/deepmerge#clone). This parameter usage seems deliberate, but it might be where the bug lies.

**Comment by robinvdvleuten** [comment]
It's now added to the interface through PR #186.
