### ISSUE TITLE
How to use with Quasar Framework SSR MODE

### ISSUE THREAD

**Issue by folamy** [robinvdvleuten/vuex-persistedstate#191]
Please I urgently need solution to this, I wish there is a way to use it with quasar SSR mode Like it is with NuxtJs plugins
It works perfectly SPA but not with SSR

**Comment by robinvdvleuten** [comment]
> If you try to report a bug but do not not provide a reproducible codesandbox or fiddle, the issue will be closed without further notice.

Please move all questions to StackOverflow please.

**Comment by ttxtosca** [comment]
@folamy Hello,

I had similar issue for some time now (eg. pre v1-beta).

The simpliest and clearer way I found was to exclude vuex-persistedstate from the app stack and use both Quasar's preFetch feature and Cookies plugin (cookies are required since localstorage data cannot be sent to server - plus, quasar's Cookies plugin has the 'key-method' parseSSR that make the wanted behavior working).

I do not have a demo app but briefly :

1. read/understand then enable preFetch feature as described here: https://v1.quasar-framework.org/quasar-cli/cli-documentation/prefetch-feature#Introduction
2. add Cookies plugin: https://v1.quasar-framework.org/quasar-plugins/cookies
3. then create your preFetch code on App, Layout or Page:
```js
import {Cookies} from 'quasar'

export default {
  preFetch ({store, ssrContext}) {
    const cookies = process.env.SERVER ? Cookies.parseSSR(ssrContext) : Cookies
    store.commit('SET_PERSISTED_DATA', cookies.get('myData'))
  }
}
```

4. finally, complete store mutation or action like this:
```js
import {Cookies} from 'quasar'

{
  state: {
    myData: {}
  },
  mutations: {
    SET_PERSISTED_DATA (data) {
      // Set cookie when SSR fetch is done (ie. only browser can set a cookie)
      if (!process.env.SERVER) {
        // Secure should be true in production (or https devel)
        Cookies.set('myData', data, {expires: 3, secure: false})
      }

      // Load/set data on both ssr fetch / regular navigation
      state.myData = data
    }
  }
}
```

I suppose that extending vuex-persistedstate config (eg. storage, getItem/setItem, getState/setState) should work but error "invalid storage" always throws ; and i struggled quite a while with that issue so.. btw, manual/low-level persistence has benefit to control a bit-more what you expect to do with data instead of just writing any change.

Hope this helps!
