### ISSUE TITLE
How can I force Vuex to reload state from localStorage?

### ISSUE THREAD

**Issue by zeroarst** [robinvdvleuten/vuex-persistedstate#234]
- `vuex-persistedstate` version:  2.5.4
- `node` version: v8.11.1
- `npm` (or `yarn`) version: 5.6.0

Relevant code or config

```javascript
```

Problem description:
I am using vuex-persistedstate with localStorage to store the data.

I am trying solve the problem where when two tabs opened, one's storage is updated, say auth token refreshed, the other tab still keeps the old state, which means it gets the old token. I guess it is cached and not load data from localStorage.

Currently I am using `window.addEventListener('storage', (e) => { })` to observe the changes and I am able to compare two tokens, if tokens are different, I manually mutate the state to the new one.

But this is not the ideal solution for me. It would be good that I can somehow force the vuex to load the data from localStroage to the state. How can I do that?

**Comment by gabrielmbmb** [comment]
Any solution to this? I'm having the same problem...

**Comment by brd6** [comment]
Same here

**Comment by dubonzi** [comment]
Same issue. I've also been using ```onstorage``` to update vuex but on a big application this can get really messy.

**Comment by gabrielmbmb** [comment]
I made a small plugin for Vuex who updates automatically the state saved in localStorage. If you want you can have a look.

**Comment by rgoupil** [comment]
@gabrielmbmb with the link it's better, isn't ?
https://github.com/gabrielmbmb/vuex-multi-tab-state

**Comment by robinvdvleuten** [comment]
You can just use eventlisteners for such usecases.

**Comment by BevanR** [comment]
```ts
// Reload state from disk when it changes in any other tab.
// @see https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event
window.addEventListener('storage', event => {
  if (event.key === 'vuex') {
    store.replaceState(JSON.parse(localStorage.vuex))
  }
})

```

**Comment by BevanR** [comment]
@robinvdvleuten You might like to document this in the README. I just about abandoned this package because you wouldn't support this feature and I didn't realise how simple this is, because the `storage` event is designed exactly for this purpose.

> This won't work on the same page that is making the changes — it is really a way for other pages on the domain using the storage to sync any changes that are made. Pages on other domains can't access the same storage objects.

— https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event

**Comment by robinvdvleuten** [comment]
@BevanR the reason that I did not mention this in the README, is simply because the plugin was never meant to be used for this use case. I already get a lot of questions related to LocalStorage in browsers and do not want even more questions about how to sync state between tabs.

**Comment by BevanR** [comment]
@robinvdvleuten Thank you for the quick answer. 🙂

That is disappointing. A lot of people are wasting a lot of effort creating less complete alternatives to this module because of your approach of avoiding even mentioning the topic, when the event listener approach seems to work very well. It does not need to be something that the module supports, and any mention of the approach could state that clearly.

Are the some drawbacks to the approach that I have not discovered yet?
