### ISSUE TITLE
Make compatible with SSR

### ISSUE THREAD

**Issue by frankspin89** [robinvdvleuten/vuex-persistedstate#44]
Would be nice if vuex-persistedstate is compatible with server side rendering.

Could be done to store the state in cookies for server side. Tried out a little example:

```
import createPersistedState from 'vuex-persistedstate'
import * as Cookies from 'js-cookie'

export const plugins = [ createPersistedState({
  getState: (key) => Cookies.getJSON(key),
  setState: (key, state) => Cookies.set(key, state, { expires: 1, secure: false })
}) ]
```
But it's failing because the defaults are referencing localStorage and window object. 

```
line 57: var storage = ref.storage; if ( storage === void 0 ) storage = window && window.localStorage;
```

Resulting in the following error:
```
ReferenceError: window is not defined
```

**Comment by zeltice** [comment]
Or make it so references to window object are removed, then on mount()  we can call some static method to restore state.

I don't mind the first frame of the app shows things in the default state (so SSR + client render are the same), but we need the references to window object removed so that the library would work in a SSR environment.

**Comment by CDuane** [comment]
Is there any update on this? I'm trying to make this work with Nuxt.js but no luck so far. Thanks.

**Comment by romandragan** [comment]
👍 same issue for me.

**Comment by robinvdvleuten** [comment]
So it turned out the customization example was currently not reflecting the latest changes to the underlaying API. I've updated it accordingly and if followed correctly, it would solve this SSR issue;

```js
import { Store } from 'vuex'
import createPersistedState from 'vuex-persistedstate'
import * as Cookies from 'js-cookie'

const store = new Store({
  // ...
  plugins: [
    createPersistedState({
      storage: {
        getItem: (key) => Cookies.getJSON(key),
        setItem: (key, value) => Cookies.set(key, value, { expires: 3, secure: true }),
        removeItem: (key) => Cookies.remove(key);
      }
    })
  ]
})
```

As you can see, you'll have to overwrite the `storage` key instead of the `getState` and `setState` keys. If it's still not working, please open another issue.

**Comment by amritk** [comment]
@robinvdvleuten this method returns the error `Invalid storage instance given`
Did something change?

**Comment by DiegoPerea** [comment]
Its not working for me. The cookie comes back to original every time i update the page,

**Comment by raymayemir** [comment]
@DiegoPerea  +

**Comment by DiegoPerea** [comment]
@raymayemir We are working around it, manually getting the cookies both in the entry-client (but it's not immediate) and in the component we are needing the data, before it requests it.
Useful info:
-Remember a coookie can only have 4kb, so maybe all your store can't live in one cookie.
-Vuex-persist (https://github.com/championswimmer/vuex-persist/) lets you reduce your store, so you save all you need in different cookies.

**Comment by edum18** [comment]
Still not working for me too... Lack of documentation

**Comment by raymayemir** [comment]
> Still not working for me too... Lack of documentation


what exactly is not working?

**Comment by bswank** [comment]
@robinvdvleuten Is there any update and/or a new issue regarding this?

I implemented your method into my Nuxt app and the cookie is being properly set, but when I load the page, I'm getting `Cookies.getJSON(key) = undefined`. Not sure why, but this has always been my issue with trying to grab cookies on the server-side of Nuxt.

Please advise, if you could!

**Comment by robinvdvleuten** [comment]
@bswank first things that comes to mind is that you have not set `secure` to `false` when writing to cookies and thus no cookie will be persisted on localhost.

**Comment by bswank** [comment]
@robinvdvleuten Thanks for your response. The cookie is being persisted just fine and secure is set to false.

The problem I've faced in the past is that I call `Cookies.set()` upon login, and on `nuxtServerInit`, or `asyncData` when I'm trying to get that cookie prior to render, it's always undefined. Your solution produces the same result.

Just wondering if this is possible to fix. I need my store/ccokies *prior* to render so I can pre-fetch data. Otherwise, I have no place to store a logged-in user ID, etc.

**Comment by robinvdvleuten** [comment]
@bswank I don't know what `nuxtServerInit` and `asyncData` does, sorry. I am not a Nuxt.js user and this library predates them. The `cookies` library does not depend on Nuxt.js, so if anything there is undefined, something else may go wrong. If you think that this is an issue with vuex-persisted state, please open a new issue with a codesandbox containing the issue. I simply do not have the time to guess everybody's Vue / Nuxt / Vuex setup.

**Comment by bswank** [comment]
@robinvdvleuten No worries; thanks anyway! Just wanted to see if your proposed solution was usable on the server-side of Nuxt.
