### ISSUE TITLE
How to invalidate the stored state?

### ISSUE THREAD

**Issue by VesterDe** [robinvdvleuten/vuex-persistedstate#7]
Hey, I would be really happy if there way an easy way to decide whether or not to actually restore the state, based on some condition.

My use case is (roughly) that I have the app running at /app, and it may or may not receive some GET parameters when it loads. If a GET parameter is equal to X, but the stored state was made with the get parameter Y, those states shouldn't override.

The only solution I can think of is to make the store key dynamic, by using the GET parameter as part of the name (eg. key = "myApp"+idFromGet), but I don't know how much of a hack that would be.

Or perhaps using js-cookie and using a dynamic key there?

Any input is much appreciated, thanks.

**Comment by robinvdvleuten** [comment]
Hi @VesterDe. If I understand your question correctly, it shouldn't be that hard. 

If you add your own `setState` method as described [here](https://github.com/robinvdvleuten/vuex-persistedstate#customization). You can do the check in the `setState` method and do nothing when you'll get the wrong parameter.

In case of restoring when your app is booting, you can override the `getState` method and return an empty object when nothing needs to be restored. As the underlaying functionality is just [a simple merge](https://github.com/robinvdvleuten/vuex-persistedstate/blob/master/src/plugin.js#L20).

Hopefully it helps, otherwise you can maybe give a more thorough code example

**Comment by VesterDe** [comment]
You understood correctly, I'll try something like what you mentioned, thanks.
